### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by r-poloni** [blobtoolkit/blobtoolkit#148]
Hi, I am producing an assembly for my species and I wanted to explore my dtaa with snailplots and contamination plots. I tried installing blobtools2 on my mac (macos 13.1), but encountered quite a few challenges. I followed the procedure recommended:
conda create -n blobtools2 -y python=3.6 docopt pyyaml ujson pysam tqdm nodejs seqtk
conda activate blobtools2
mkdir -p taxdump
cd taxdump
curl -L ftp://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz | tar xzf -
cd ..
git clone https://github.com/blobtoolkit/blobtools2
git clone https://github.com/blobtoolkit/viewer
cd viewer
npm install

The last command gave me a lot of errors, probably due to an old version of npm install. Here is the error message when running npm install and the logfile.
Thanks!

npm ERR! code 127
npm ERR! path /Users/riccardo/environments/viewer/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | darwin | x64
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /Users/riccardo/miniconda3/envs/blobtools2/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                                ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Darwin 22.2.0
npm ERR! gyp ERR! command "/Users/riccardo/miniconda3/envs/blobtools2/bin/node" "/Users/riccardo/environments/viewer/node_modules/.bin/node-gyp" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/riccardo/environments/viewer/node_modules/fibers
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! sh: nodejs: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/riccardo/.npm/_logs/2023-02-21T14_22_21_482Z-debug.log
[2023-02-21T14_22_21_482Z-debug.log](https://github.com/blobtoolkit/blobtoolkit/files/10794482/2023-02-21T14_22_21_482Z-debug.log)

**Comment by sujaikumar** [comment]
Hi there. Apologies for not updating the documentation everywhere, but the latest version is hopefully even easier to install than the steps above:

Let's say you want to call the conda environment `btk`, then you need to first create the environment and make sure it has pip, then activate it, and lastly pip install blobtoolkit

```
conda create -n btk pip
conda activate btk
pip install blobtoolkit[full]
```

To test the install, just type:
```
blobtools host _
```
`_` refers to the test directory that ships with blobtoolkit.

You should see a message like:
```
Starting BlobToolKit API on port 8000 (pid: 50245)
Starting BlobToolKit viewer on port 8080 (pid: 50247)
Visit http://localhost:8080 to use the interactive BlobToolKit Viewer.
```
You might get some pop ups asking you to allow access to a port - feel free to say deny (as you do not need to allow access from outside your machine)

If you go to your web browser and type: localhost:8080 in the URL bar - you should see the BTK interface (and searching for "all" will show you the example blobdir)

**Comment by r-poloni** [comment]
Hi! Thank you for the quick answer. I am actually a bit confused since there is BlobToolKit, blobtools, Viewer, and you don't understand what you are installing when running pip.
I just tried the procedure suggested but it's not working.
pip install blobtoolkit[full] gives error 

`zsh: no matches found: blobtoolkit[full]`

If I try to install the minimal (only blobtools) it goes on smoothly but when I run blobtools host _ it gives error:
```
Traceback (most recent call last):
  File "/Users/riccardo/miniconda3/envs/btk/bin/blobtools", line 5, in <module>
    from blobtools import cli
ModuleNotFoundError: No module named 'blobtools'
```

**Comment by sujaikumar** [comment]
Hi. I've changed one line in my answer above (to make it easier for anyone else following the thread).

Can you try removing the env first:
```
conda deactivate
conda env remove -n btk
```

and starting again, this time with python 3.9 (it is possible that your default conda python is too new! :-))
```
conda create -n btk python=3.9 pip
conda activate btk
pip install blobtoolkit[full]
```

**Comment by r-poloni** [comment]
Hi, sorry, maybe I am just missing something important, but pip does not know how to get the [full] version. I tried again and I get the same error. In the pip page I only see the command pip blobtoolkit, but not the [full] option

**Comment by sujaikumar** [comment]
Hi. Thanks for trying.

I think zsh is trying to expand the [] (I'm using bash)

Can you try putting single quotes like this
```
pip install 'blobtoolkit[full]'
```

**Comment by sujaikumar** [comment]
Hi. Thanks for trying.

I think zsh is trying to expand the [] (I'm using bash)

Can you try putting single quotes like this
```
pip install 'blobtoolkit[full]'
```

**Comment by renaschweizer** [comment]
Thank you for opening this issue @r-poloni. I was having the same problems and confusion with installation. The most recent suggestion from @sujaikumar worked for me and I am now able to use the viewer!

**Comment by r-poloni** [comment]
Hi! Thank you, it actually managed to launch pip, but there are problems wirh subprocesses (build wheels for datried). When I try to launch "blobtoolkit host _" itexits with "command not found" error. It is certainly not installed because when I check the packages installed there is not blotoolkit.

Riccardo

**Comment by rjchallis** [comment]
This looks like a python version problem, either not picking up the conda installed version, or conda still having a version other than 3.9/3.10. Blobtoolkit v4 has proven to be a little more fussy about versions on Mac than I realised when I set the list of compatible versions in pip. What do you get if you run:

```
which python
```

and 

```
python --version
```

**Comment by r-poloni** [comment]
Hi. If I launch the command into btk environment it takes correctly the bin file of python into btk env, and gets python 3.9.16 version. Outside the environment it is python 3.9.6, so, even if pip is supposed to run inside the btk environmentk, even outside it should be ok.
Sorry for such a complicate issue!

**Comment by rjchallis** [comment]
could be stuck with something in the cache. Can you try 

```
pip uninstall blobtoolkit
pip install --no-cache-dir 'blobtoolkit[full]'
```

**Comment by r-poloni** [comment]
Hi, I tried but it still gives the same error:

     error: command '/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_abtkjzimv1/croot/python-split_1673452680692/_build_env/bin/llvm-ar' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for datrie
  Building wheel for stopit (setup.py) ... done
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11937 sha256=fda70eb6c5fb131021da7757368051c15d7031a14a08a5766837a4a66d3e086b
  Stored in directory: /private/var/folders/4g/7yd5dr590552npzvyw6gkm040000gn/T/pip-ephem-wheel-cache-vjymqsl6/wheels/3f/2c/f9/411eea50089f1313eb80637f6107ec839721f6e36679050160
Successfully built blobtoolkit-host blobtoolkit-pipeline chromedriver-binary-auto docopt blobtoolkit connection-pool stopit
Failed to build datrie
ERROR: Could not build wheels for datrie, which is required to install pyproject.toml-based projects

**Comment by sujaikumar** [comment]
This might sound extreme (and apologies if you've already tried it), but would it be worth starting with a new conda installation? or upgrading the base conda?

The reason I say this is that I just tried these instructions on a new linux machine as well and that worked. So it is possible that there is something in previous installs preventing datrie from being installed correctly which might explain your error messages.

**Comment by r-poloni** [comment]
Hi, I already tried to re install python on all the machine, then conda and the try again everything but didn't work. I'll try again or maybe I should consider installing everything in the cluster. The problem is that you cannot visualise plots...

**Comment by IvonedeBem** [comment]
Hi all, Thank you, @r-poloni for posting your problem. I am having the exact same problem when trying to install it here. I have tested every point discussed in this thread, and nothing works. Have any of you ever figured out how to install it?

**Comment by rjchallis** [comment]
Hi @IvonedeBem, could you please confirm what error you see if you run the commands:
```
conda create -n btk_issue_148 python=3.10 pip
conda activate btk_issue_148
pip install "blobtoolkit[full]"
blobtools host _
```
