### ISSUE TITLE
Issue with view when trying to export snail plot

### ISSUE THREAD

**Issue by MikeSanJose** [blobtoolkit/blobtoolkit#155]
I am trying to export a snail plot of my genome but am getting this error. 

Any help would be appreciated 

blobtools view --view snail H_kahamanoa                                                                                                
Initializing viewer
Traceback (most recent call last):
  File "/home/mdsjose/.local/lib/python3.9/site-packages/blobtools/lib/view.py", line 284, in static_view
    driver, display = firefox_driver(args)
  File "/home/mdsjose/.local/lib/python3.9/site-packages/blobtools/lib/view.py", line 206, in firefox_driver
    driver = webdriver.Firefox(
  File "/home/mdsjose/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 179, in __init__
    RemoteWebDriver.__init__(
  File "/home/mdsjose/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mdsjose/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mdsjose/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/mdsjose/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 255
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/mdsjose/.local/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/home/mdsjose/.local/lib/python3.9/site-packages/blobtools/blobtools.py", line 88, in cli
    sys.exit(subcommand())
  File "/home/mdsjose/.local/lib/python3.9/site-packages/blobtools/lib/view.py", line 491, in cli
    main(args)
  File "/home/mdsjose/.local/lib/python3.9/site-packages/blobtools/lib/view.py", line 474, in main
  File "/opt/apps/software/lang/Anaconda3/2022.05/lib/python3.9/traceback.py", line 167, in format_exc
    static_view(args, loc, viewer)
  File "/home/mdsjose/.local/lib/python3.9/site-packages/blobtools/lib/view.py", line 286, in static_view
    format_exc(err)
  File "/opt/apps/software/lang/Anaconda3/2022.05/lib/python3.9/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/opt/apps/software/lang/Anaconda3/2022.05/lib/python3.9/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/opt/apps/software/lang/Anaconda3/2022.05/lib/python3.9/traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "/opt/apps/software/lang/Anaconda3/2022.05/lib/python3.9/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'WebDriverException' and 'int'

**Comment by rjchallis** [comment]
Hi sorry for the delay getting back to you on this. I'm not sure what is happening here. Could you give let me know which version this is happening with and what command you used to install blobtools
