### ISSUE TITLE
selenium.common.exceptions.TimeoutException during `view` operation in Docker

### ISSUE THREAD

**Issue by bgruening** [blobtoolkit/blobtoolkit#157]
Hi,

we want to run the official Docker container on a cluster but the tool reproducible crashes during the `view` step.

Any idea how to solve or work around this error?

Thanks a lot.

```
Initializing viewer
Traceback (most recent call last):
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/view.py", line 300, in static_view
    driver, display = firefox_driver(args)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/view.py", line 212, in firefox_driver
    driver = webdriver.Firefox(
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Failed to read marionette port


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/btk_env/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/view.py", line 495, in cli
    main(args)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/view.py", line 480, in main
    static_view(args, loc, viewer)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/view.py", line 302, in static_view
    format_exc(err)
  File "/opt/conda/envs/btk_env/lib/python3.9/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/opt/conda/envs/btk_env/lib/python3.9/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/opt/conda/envs/btk_env/lib/python3.9/traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "/opt/conda/envs/btk_env/lib/python3.9/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'TimeoutException' and 'int'
```

**Comment by rjchallis** [comment]
Hi. I've been unable to reproduce this so I'm unsure what is causing the issue. Could you let me know which container version you are running and what command and I can try to dig a little deeper
