### ISSUE TITLE
Editing source code when installed using pip

### ISSUE THREAD

**Issue by sheinasim** [blobtoolkit/blobtoolkit#158]
Hello there! 

I successfully installed the current version of blobtools[full] using pip, and while I can get some functions to work, there are others that can't because of some incompatibility issues (such as python/node/npl). None the less, I can host a local instance of the interactive viewer and I was hoping to make a small edit to the source code to print "contig" instead of "scaffold." 

The files I edited before were called summary.js and SnailPlot.jsx. However, when I try to find them in the pip install path, I cannot as the file structure is not the same. Do you know where in the pip install path I can make those edits?

Thanks!
Sheina

**Comment by sheinasim** [comment]
Thank you!

I tried running the package-ui.sh after installing node and npm using nvm locally, but it's not successful with these errors:

```gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/sheinasim/miniconda3/bin/python" is v3.10.9, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/sheinasim/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/sheinasim/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:273:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Users/sheinasim/.nvm/versions/node/v8.17.0/bin/node" "/Users/sheinasim/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/sheinasim/Software/blobtoolkit_scaffold/src/viewer/node_modules/fibers
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@5.0.3 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@5.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

Attached is the .log file as well.

Any help would be appreciated, I've been trying to install the viewer for days.

[2023-03-27T20_14_34_235Z-debug.log](https://github.com/blobtoolkit/blobtoolkit/files/11082727/2023-03-27T20_14_34_235Z-debug.log)

Best wishes,
Sheina

**Comment by rjchallis** [comment]
The UI is usually built automatically using this action: https://github.com/blobtoolkit/blobtoolkit/blob/main/.github/workflows/package-ui.yml - it should just need node v16 and the pkg npm package that I missed last time

The message you are getting suggests that you have an old version of nodes in your environment.

To run the package-ui script it will be best to make a new conda environment (or use a fresh VM).  Something like:

```
conda create -n build-ui python=3.9 nodejs=16
conda activate build-ui
npm install -g pkg
./package-ui.sh
```

Hope this helps

**Comment by sheinasim** [comment]
Hi Richard,

Thank you so much for your patience with me on this. I did exactly as you said:

```conda create -n build-ui python=3.9 nodejs=16
conda activate build-ui
npm install -g pkg
./package-ui.sh 
```

And I receive what I think are the same errors as before. 

Should I delete the environment, delete the repo and start again? Would that help?

Thanks!
Sheina
[2023-03-30T01_43_42_065Z-debug.log](https://github.com/blobtoolkit/blobtoolkit/files/11106992/2023-03-30T01_43_42_065Z-debug.log)

**Comment by rjchallis** [comment]
Hi Sheina

I think deleting everything and starting again may help - It's likely that the node-modules folder has some incompatible versions already installed that are not being replaced. I've had time to look at the code to make this easier to change and should be able to make this much simpler by setting the text to contig if the assembly level in the blobdir meta.json file is contig. I'll make those changes now and should be able to get a new release out fairly quickly.

**Comment by rjchallis** [comment]
I've not got the release workflow smoothed out for viewer updates just yet, this will make it into a future blobtoolkit release but meanwhile you can fetch pre-built copies of the new viewer and api binaries from https://github.com/blobtoolkit/blobtoolkit/suites/12040037993/artifacts/632987801 - this is a direct link to a directory with versions of the binaries for various operating systems that get built as part of the GitHub action that runs automated checks on each commit. The directory above is from this run https://github.com/blobtoolkit/blobtoolkit/actions/runs/4616434849.

If you add the appropriate binaries to your path they should be picked up in preference to the default versions when you run the pip-installed blobtools view/host commands. If the blobdir has
```
assembly:
    level: contig
    ...
```
in meta.json(.gz) then the snail plot will display contig instead of scaffold

**Comment by sheinasim** [comment]
Hi Richard,

Thank you so much for all your help with this. Some good and bad news. I deleted my environment, deleted the repo, re-created the environment and downloaded the binaries you sent and put them in my path.

My path is now this:

`/Users/sheinasim/.nvm/versions/node/v16.19.1/bin:/Users/sheinasim/miniconda3/envs/btk_env/bin:/Users/sheinasim/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/sheinasim/Software/blobtoolkit/node/blobtoolkit-viewer-macos`

and the head of my meta.json for a blobdir is:

`{
 "id": "idCulQuin_purged_ec",
 "assembly": {
  "level: contig",
  "file": "idCulQuin_purged_ec.fasta",
  "scaffold-count": 629,
  "span": 607348780
 },`

Unfortunately, the snail plot is still reporting "Scaffold." Not sure if I followed your directions correctly. However, if an update to the main branch/pip install is pending, I can definitely wait!

Thanks again!
Sheina

**Comment by rjchallis** [comment]
Hi Sheina

The latest release (4.1.5) ought to label the snail plots with contig if the assembly level is contig. If not I've also made an early version of the new command line plotting code available. This can do snail plots that use assembly level in the plot tables (and blobs that aren't quite feature complete yet). To try it out you can 
```
conda install -c tolkit blobtk
```
then

``` 
blobtk plot -v snail -d /path/to/dataset -o snail.png
blobtk plot -v blob -d /path/to/dataset -o blob.png
```

**Comment by sheinasim** [comment]
Hi Richard,

Thanks for this!

I installed using conda blobtk but now I'm getting the error 

```
blobtk: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by blobtk)
blobtk: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by blobtk)
blobtk: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by blobtk)
blobtk: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by blobtk)
blobtk: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by blobtk)
blobtk: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by blobtk)
blobtk: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by blobtk)
blobtk: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by blobtk)
blobtk: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by blobtk)
```

Is this a nodejs library?

Thanks!
Sheina

**Comment by sheinasim** [comment]
Hi Richard,

I tried running with the docker/singularity image and got this error:

```
singularity exec blobtk_latest.sif blobtk plot -v snail -d icAcaAest_primary_purged_ec -o snail.png

thread 'main' panicked at 'unable to parse json: Error("missing field `prefix`", line: 7, column: 2)', src/blobdir.rs:195:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

And `ldd --version` yields this:

```
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by rjchallis** [comment]
ah - I'd accidentally made assembly.prefix a required field. I've updated the docker image so that error shouldn't get thrown.

and thanks for letting me know your GLIBC version - useful to know which versions might need supporting with a cross-compiled binary in case docker/singularity is not an option

**Comment by sheinasim** [comment]
Hi Richard,

Thanks for making that change!

New error now:

```
icAcaAest_primary_purged_ec_figures_ctg/snail.png -d icAcaAest_primary_purged_ec
thread 'main' panicked at 'unable to parse json: Error("missing field `name`", line: 551, column: 12)', src/blobdir.rs:203:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

Looks like I just need to create a field "name" in a json file. Do you know which json, where "name" should go, and what should be assigned to it?

Thanks!
Sheina

**Comment by rjchallis** [comment]
This will be in `meta.json`, and is either referring to the dataset name, which should be a top-level field alongside `id` and is the name of the dataset, or the taxon name, which belongs in the `taxon` section and should be the species/subspecies name.

**Comment by sheinasim** [comment]
Hi Richard,

I tried manually editing the meta.json file to look like this:

```
 "taxon": {
   "name": "Acalolepta aesthetica"
},
```

and I got this error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/plot.rs:144:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

So it looks like it's looking for "name" under taxon, but it doesn't like the name I'm giving it?

**Comment by rjchallis** [comment]
I've tried a couple of approaches to fixing this - the binary now has better error handling and can tolerate most fields being empty (and prints more informative error messages rather than crashing), so hopefully that will be a bit easier to use if you pull the 0.3.6 docker image.

I've also compiled the binary with static rather than dynamic links to hopefully make the GLIBC version issues go away. The condo release step isn't working for me for now, but if you want to try running the executable directly it is available at https://github.com/blobtoolkit/blobtk/releases/download/0.3.6/blobtk-linux

Hope at least one of these options works for you

**Comment by sheinasim** [comment]
Dear Richard,

Thanks!

This last version of docker did it for me and now it says "contig" when I add the level the meta.json file.

Thank you so so much, I really appreciate this!

Best wishes,
Sheina
