### ISSUE TITLE
Issue in running any filter commands

### ISSUE THREAD

**Issue by myco-bradshaw** [blobtoolkit/blobtoolkit#161]
Hello, 

I am having some issues with running any filter commands (fasta or fastq). After creating the filtered blobdir however, it always errors out with:

Traceback (most recent call last):
  File "/home/abradshaw/miniconda3/envs/btk_env/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/home/abradshaw/miniconda3/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/home/abradshaw/miniconda3/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/filter.py", line 462, in cli
    main(args)
  File "/home/abradshaw/miniconda3/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/filter.py", line 318, in main
    field["module"].apply_filter(ids, args[field["flag"]], **args)
  File "/home/abradshaw/miniconda3/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/cov.py", line 90, in apply_filter
    filter.fastx(options)
TypeError: fastx() takes 0 positional arguments but 1 was given

I have tried uninstalling and reinstalling the environment as well as a number of different filtering combinations, of which only the --table seems to work creating the correct filtered tsv file. Below is the command I have been attempting to use to filter.  Am I inputting the command incorrectly or is there an issue with the current pip install?

blobtools filter \
--param bestsumorder_phylum--Inv=no-hit \
--param bestsumorder_kingdom--Inv=Fungi \
--fastq /path/read.trimmed.1.fastq.gz \
--fastq /path/read.trimmed.2.fastq.gz \ 
--cov *.sorted.bam \
--output ./blobtools2/Fungi_nohit_filtered \
./blobtools2

**Comment by rjchallis** [comment]
Hi, sorry, this is a bug in the way the filtering functions are called. I updated the functions to use keyword rather than positional arguments but forgot to change the way I called them from blobtools. I'll fix this for the next release
