### ISSUE TITLE
Cannot add blast outputs to blobtools directory

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [blobtoolkit/blobtoolkit#17]
Hello,

I have been trying to add my BLAST and DIAMOND outputs to the blobtools directory, but I have been failing to add any of the two. 

I get the following error:
```
Traceback (most recent call last):
  File "/dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuy/programs/blobtoolkit/blobtools2/lib/add.py", line 165, in <module>
    main()
  File "/dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuy/programs/blobtoolkit/blobtools2/lib/add.py", line 132, in main
    meta=meta)
  File "/dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuy/programs/blobtoolkit/blobtools2/lib/hits.py", line 292, in parse
    blast = parse_blast(file, cols, None, index, float(kwargs['--evalue']), float(kwargs['--bitscore']))
  File "/dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuy/programs/blobtoolkit/blobtools2/lib/hits.py", line 27, in parse_blast
    if evalue < float(row[cols['evalue']]):
IndexError: list index out of range
```

I suppose then that my blast files do not look as they should. For BLAST I was able to run it with the command line given in the tutorial, but not for DIAMOND. 

This is how my BLAST output looks:
```
3C-assembly|contig_17	N/A	147	LR812526.1	77.87	244	48	3	3099	3341	62716373	62716611	4e-29
3C-assembly|contig_141	N/A	219	CP000962.1	76.48	438	81	15	21750	22185	3518716	3519133	9e-51
3C-assembly|contig_141	N/A	213	CP046450.1	76.26	438	82	15	21750	22185	2952814	2952397	4e-49
3C-assembly|contig_141	N/A	213	CP031098.1	76.26	438	82	15	21750	22185	3306971	3306554	4e-49
3C-assembly|contig_141	N/A	213	CP028859.1	76.26	438	82	15	21750	22185	3456515	3456932	4e-49
3C-assembly|contig_141	N/A	213	CP028842.1	76.26	438	82	15	21750	22185	3411794	3412211	4e-49
3C-assembly|contig_141	N/A	213	CP014219.1	76.26	438	82	15	21750	22185	3509422	3509839	4e-49
3C-assembly|contig_141	N/A	213	CP014174.1	76.26	438	82	15	21750	22185	3578386	3578803	4e-49
3C-assembly|contig_141	N/A	213	CP013850.1	76.26	438	82	15	21750	22185	3601574	3601991	4e-49
3C-assembly|contig_141	N/A	213	CP013847.1	76.26	438	82	15	21750	22185	3644169	3644586	4e-49
```

And this is how the DIAMOND output looks:
```
3C-assembly|contig_2	240159	109.4
3C-assembly|contig_2	240159	103.2
3C-assembly|contig_2	67767	94.0
3C-assembly|contig_2	7668	94.0
3C-assembly|contig_2	7668	92.8
3C-assembly|contig_2	7668	92.0
3C-assembly|contig_2	7668	92.0
3C-assembly|contig_2	7668	92.0
3C-assembly|contig_2	7668	91.7
3C-assembly|contig_2	7668	90.9
```

**Comment by rjchallis** [comment]
Hi

You can use the `--hits-cols` option in `blobtools add` to set the column numbers to import. The default values should match the outputs from the example commands but it looks like you have fewer columns than expected for Diamond in particular. Did you manage to set up the database as in the [install instructions](https://blobtoolkit.genomehubs.org/install/)?

**Comment by jdmillwood** [comment]
Hi, I am having a similar issue with importing my Blast file. I followed the given instructions for running BLAST and importing the BLAST.out file into my Blob directory. I receive the following error:
```
Loading parsed taxdump
bestsumorder
Traceback (most recent call last):
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/add.py", line 165, in <module>
    main()
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/add.py", line 132, in main
    meta=meta)
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/hits.py", line 292, in parse
    blast = parse_blast(file, cols, None, index, float(kwargs['--evalue']), float(kwargs['--bitscore']))
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/hits.py", line 27, in parse_blast
    if evalue < float(row[cols['evalue']]):
IndexError: list index out of range
```


My BLAST output looks like this:
```
contig_10_pilon_pilon_pilon_pilon	31234	13516	gi|308480307|ref|XM_003102313.1|	99.53	7441	1	11	381317	388755	7539	131	0.0
contig_10_pilon_pilon_pilon_pilon	31234	9154	gi|308480034|ref|XM_003102177.1|	96.88	5479	154	6	2750890	2756352	336	5813	0.0
contig_10_pilon_pilon_pilon_pilon	31234	9046	gi|308471311|ref|XM_003097839.1|	97.14	5358	152	1	1156684	1162040	6999	1642	0.0
contig_10_pilon_pilon_pilon_pilon	31234	8900	gi|308488054|ref|XM_003106174.1|	97.28	5249	141	1	1156598	1161844	7656	2408	0.0
contig_10_pilon_pilon_pilon_pilon	31234	8648	gi|308470669|ref|XM_003097520.1|	97.03	5143	152	1	1156703	1161844	7586	2444	0.0
contig_10_pilon_pilon_pilon_pilon	31234	8545	gi|308484914|ref|XM_003104609.1|	96.94	5095	156	0	1156946	1162040	7036	1942	0.0
contig_10_pilon_pilon_pilon_pilon	31234	8381	gi|308455389|ref|XM_003090188.1|	95.99	5161	204	3	1156684	1161842	7716	2557	0.0
contig_10_pilon_pilon_pilon_pilon	31234	7945	gi|308454195|ref|XM_003089700.1|	100.00	4302	0	0	1156767	1161068	4302	1	0.0
```

I was able to add my Diamond output without any issues.

I tried using `--hits-cols`, but that didn't work either. It gave me this error:

```Loading parsed taxdump
bestsumorder
Traceback (most recent call last):
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/add.py", line 165, in <module>
    main()
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/add.py", line 132, in main
    meta=meta)
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/hits.py", line 292, in parse
    blast = parse_blast(file, cols, None, index, float(kwargs['--evalue']), float(kwargs['--bitscore']))
  File "/home/jmsutton/blobtoolkit/blobtools2/lib/hits.py", line 34, in parse_blast
    'start': int(row[cols['sstart']])+offset,
ValueError: invalid literal for int() with base 10: '99.53'
```

**Comment by rjchallis** [comment]
I would expect the blast output format `6 qseqid staxids bitscore std` (as in the [adding hits page](https://blobtoolkit.genomehubs.org/blobtools2/blobtools2-tutorials/adding-data-to-a-dataset/adding-hits/#hits)) to give you an output file with 14 columns, but you only have 13 so the expected e-value column index is out of range. 

You should be able to import this using `--hits-cols 1=qseqid,2=staxids,3=bitscore,4=sseqid,9=sstart,10=send,13=evalue` 

As for working out why your file is different than the expectation, it looks like it is missing column 4, which would be a repeat of the qseqid. This is redundant as it is already implied by std, but is in my recent blast outputs using blast v2.10.1. Which blast version are you using?

**Comment by athenasyarifa** [comment]
Hi Richard, 
I also have the same error with a little difference in the last sentence of the error, see the following: 

`Loading parsed taxdump
Traceback (most recent call last):
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/blobtools2/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/blobtools2/lib/python3.7/site-packages/blobtools/blobtools.py", line 88, in cli
    sys.exit(subcommand())
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/blobtools2/lib/python3.7/site-packages/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/blobtools2/lib/python3.7/site-packages/blobtools/lib/add.py", line 154, in main
    meta=meta
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/blobtools2/lib/python3.7/site-packages/blobtools/lib/hits.py", line 523, in parse
    float(kwargs["--bitscore"]),
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/blobtools2/lib/python3.7/site-packages/blobtools/lib/hits.py", line 28, in parse_blast
    for line in file_io.stream_file(blast_file):
TypeError: 'NoneType' object is not iterable
`

I followed exactly the installation page, so my blast output has 14 columns as instructed. Do you have any suggestions on what I should do? Many thanks in advance!

Best, 
Rifa
