### ISSUE TITLE
Error while trying to add "TypeError: '<' not supported between instances of 'NoneType' and 'int'"

### ISSUE THREAD

**Issue by jodysnl** [blobtoolkit/blobtoolkit#174]
Hi,

I was running the command line to add hits into my blobtoolkit file (command just below) but the run fail and end with an error.
Could you help me identify the problem?
I installed the blobtoolkit with conda.

`blobtools add --hits blastn.out --hits diamond.blastx.out --taxrule bestsumorder --taxdump ./taxdump/ ./btk`
I also tried with `blobtools add --hits blastn.out --taxdump ./taxdump/ ./btk `
and it doesn't work

Here is the error I'm getting: 
```
Loading parsed taxdump
Traceback (most recent call last):
File "/home/unamur/URBE/jody/miniconda3/envs/envbtk/bin/blobtools", line 8, in
sys.exit(cli())
File "/home/unamur/URBE/jody/miniconda3/envs/envbtk/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
sys.exit(subcommand())
File "/home/unamur/URBE/jody/miniconda3/envs/envbtk/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
main(args)
File "/home/unamur/URBE/jody/miniconda3/envs/envbtk/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
parsed = field["module"].parse(
File "/home/unamur/URBE/jody/miniconda3/envs/envbtk/lib/python3.9/site-packages/blobtools/lib/hits.py", line 525, in parse
bins = bin_hits(
File "/home/unamur/URBE/jody/miniconda3/envs/envbtk/lib/python3.9/site-packages/blobtools/lib/hits.py", line 166, in bin_hits
hits = sorted(blast[identifier], key=get_item)
TypeError: '<' not supported between instances of 'NoneType' and 'int'

```
Thank you

**Comment by rjchallis** [comment]
This could be a problem with parsing the blast output file. Could you share the first few lines so I can take a look?
