### ISSUE TITLE
Blobtools add --cov error.

### ISSUE THREAD

**Issue by COCOJJLEE** [blobtoolkit/blobtoolkit#180]
**Environment:**
Centos7
Python = 3.9.13
blobtoolkit = 4.1.4

**Input data processing:**
pacbio hifi read
minimap2 -ax asm20 ${organism}.asm.p_ctg.fa ${organism}.cutadapt.output.fastq > ${organism}.sam
samtools view -Sb ${organism}.sam > ${organism}.bam
samtools sort ${organism}.bam > ${organism}.sort.bam
samtools index ${organism}.sort.bam

**Error command:**
blobtools add --cov ${organism}.sort.bam BlobDir/

**Error message:**
Traceback (most recent call last):
  File "/home/.conda/envs/blobtools/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/home/.conda/envs/blobtools/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/home/.conda/envs/blobtools/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/home/.conda/envs/blobtools/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
    parsed = field["module"].parse(
  File "/home/.conda/envs/blobtools/lib/python3.9/site-packages/blobtools/lib/cov.py", line 182, in parse
    fields = parse_bam(
  File "/home/.conda/envs/blobtools/lib/python3.9/site-packages/blobtools/lib/cov.py", line 43, in parse_bam
    os.remove(index_file)
FileNotFoundError: [Errno 2] No such file or directory: 'Elophila_nymphaeata.sort.bam.csi'

When I ran that task 3 months ago, it worked fine, but I recently encountered the issue.
Is there any way to fix this?
blobtools add --busco and blobtools create --fasta work well

Sincerely

**Comment by tanpham15** [comment]
Hi, I got the similar error, and it looks like no index file, .csi in your directory 

I think you might need to index the bam file again (samtools index -c name.sort.bam). Note: also you should remove the bam.bai before `blobtools add --busco`. When I have both .bai and .csi, the error occurred.

Good luck.
