### ISSUE TITLE
pip install blobtoolkit[full] error: Failed building wheel for blobtk

### ISSUE THREAD

**Issue by Surbhigrewal** [blobtoolkit/blobtoolkit#186]
Hi I am trying to install on intel cpu Mac and get the following error

```
Building wheels for collected packages: blobtk 
Building wheel for blobtk (pyproject.toml) ... error
error: subprocess-exited-with-error

  
  × Building wheel for blobtk (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      Running 'maturin pep517 build-wheel -i /Users/sbzsm11/mambaforge/envs/btk/bin/python --compatibility off'
      warning: unused manifest key: aarch64-apple-darwin
      warning: unused manifest key: target.x86_64-unknown-linux-gnu.rustflags
         Compiling autocfg v1.1.0
         Compiling libc v0.2.147
         Compiling proc-macro2 v1.0.66
         Compiling unicode-ident v1.0.11
         Compiling cfg-if v1.0.0
         Compiling pkg-config v0.3.27
         Compiling bytemuck v1.14.0
         Compiling target-lexicon v0.12.11
         Compiling syn v1.0.109
         Compiling memchr v2.6.3
         Compiling scopeguard v1.2.0
         Compiling crossbeam-utils v0.8.16
         Compiling arrayvec v0.7.4
         Compiling serde v1.0.188
         Compiling simd-adler32 v0.3.7
         Compiling crc32fast v1.3.2
         Compiling adler v1.0.2
         Compiling vcpkg v0.2.15
         Compiling num-traits v0.2.16
         Compiling memoffset v0.9.0
         Compiling crossbeam-epoch v0.9.15
         Compiling miniz_oxide v0.7.1
         Compiling kurbo v0.9.5
         Compiling log v0.4.20
         Compiling version_check v0.9.4
         Compiling pyo3-build-config v0.18.3
         Compiling quote v1.0.33
         Compiling jobserver v0.1.26
         Compiling smallvec v1.11.0
         Compiling once_cell v1.18.0
         Compiling siphasher v0.3.11
         Compiling syn v2.0.31
         Compiling cc v1.0.83
         Compiling flate2 v1.0.27
         Compiling slotmap v1.0.6
         Compiling rayon-core v1.11.0
         Compiling unicode-general-category v0.6.0
         Compiling unicode-bidi v0.3.13
         Compiling svgtypes v0.11.0
         Compiling cmake v0.1.50
         Compiling bitflags v1.3.2
         Compiling crossbeam-deque v0.8.3
         Compiling float-cmp v0.9.0
         Compiling num_cpus v1.16.0
         Compiling crossbeam-channel v0.5.8
         Compiling strict-num v0.1.1
         Compiling aho-corasick v1.0.5
         Compiling num-integer v0.1.45
         Compiling rustversion v1.0.14
         Compiling quick-error v1.2.3
         Compiling fnv v1.0.7
         Compiling ident_case v1.0.1
         Compiling tinyvec_macros v0.1.1
         Compiling bzip2-sys v0.1.11+1.0.8
         Compiling libz-sys v1.1.12
         Compiling lzma-sys v0.1.20
         Compiling curl-sys v0.4.65+curl-8.2.1
         Compiling lazy_static v1.4.0
         Compiling semver v0.1.20
         Compiling ttf-parser v0.18.1
         Compiling paste v1.0.14
         Compiling xmlparser v0.13.5
         Compiling heck v0.4.1
         Compiling rctree v0.5.0
      error: failed to run custom build command for libz-sys v1.1.12
      
      Caused by:
        process didn't exit successfully: `/private/var/folders/6v/j50zbmcn1wscg_m94xzhc9k00000gp/T/pip-install-uoiltuxv/blobtk_c3c81b2d5e214efa961a024d5cf98122/target/release/build/libz-sys-e693d9196898efc7/build-script-build` (exit status: 101)
        --- stdout
        cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
        cargo:rerun-if-changed=build.rs
        CMAKE_TOOLCHAIN_FILE_x86_64-apple-darwin = None
        CMAKE_TOOLCHAIN_FILE_x86_64_apple_darwin = None
        HOST_CMAKE_TOOLCHAIN_FILE = None
        CMAKE_TOOLCHAIN_FILE = None
        CMAKE_GENERATOR_x86_64-apple-darwin = None
        CMAKE_GENERATOR_x86_64_apple_darwin = None
        HOST_CMAKE_GENERATOR = None
        CMAKE_GENERATOR = None
        CMAKE_PREFIX_PATH_x86_64-apple-darwin = None
        CMAKE_PREFIX_PATH_x86_64_apple_darwin = None
        HOST_CMAKE_PREFIX_PATH = None
        CMAKE_PREFIX_PATH = None
        CMAKE_x86_64-apple-darwin = None
        CMAKE_x86_64_apple_darwin = None
        HOST_CMAKE = None
        CMAKE = None
        running: cd "/private/var/folders/6v/j50zbmcn1wscg_m94xzhc9k00000gp/T/pip-install-uoiltuxv/blobtk_c3c81b2d5e214efa961a024d5cf98122/target/release/build/libz-sys-0deea439487bc301/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/sbzsm11/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libz-sys-1.1.12/src/zlib-ng" "-DCMAKE_OSX_ARCHITECTURES=x86_64" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/private/var/folders/6v/j50zbmcn1wscg_m94xzhc9k00000gp/T/pip-install-uoiltuxv/blobtk_c3c81b2d5e214efa961a024d5cf98122/target/release/build/libz-sys-0deea439487bc301/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
      
        --- stderr
        Traceback (most recent call last):
          File "/Users/sbzsm11/mambaforge/envs/btk/bin/cmake", line 5, in <module>
            from cmake import cmake
        ModuleNotFoundError: No module named 'cmake'
        thread 'main' panicked at '
        command did not execute successfully, got: exit status: 1
      
        build script failed, must exit now', /Users/sbzsm11/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `"cargo" "rustc" "--release" "--message-format" "json" "--lib" "--crate-type" "cdylib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/blobtk.cpython-39-darwin.so"`
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.9 at /Users/sbzsm11/mambaforge/envs/btk/bin/python
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/sbzsm11/mambaforge/envs/btk/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for blobtk
Failed to build blobtk
ERROR: Could not build wheels for blobtk, which is required to install pyproject.toml-based projects`
```

I have tried
```
pip install cmake --upgrade
pip install wheel setuptools --upgrade
```

I have rustc version 1.72.0 (5680fa18f 2023-08-23) (Homebrew)

**Comment by Surbhigrewal** [comment]
So restarting and installing cmake while making the environment 

`mamba create -n btk -c conda-forge python=3.9 cmake -y`

got past the above error

 ```
Building wheel for blobtk (pyproject.toml) ... done
  Created wheel for blobtk: filename=blobtk-0.4.6-cp39-cp39-macosx_10_7_x86_64.whl size=1437099 sha256=106ff6071622f13987b57272425c42c22c56435893c79649f564ba64f76545b8
  Stored in directory: /Users/sbzsm11/Library/Caches/pip/wheels/87/99/1d/b9b22e7cde88608d2dc621b01bdc249b27a5724bc19481f5f0
Successfully built blobtk
```

But now when I test if the installation was successful I get this error:

```
$blobtools
Traceback (most recent call last):
  File "/Users/sbzsm11/mambaforge/envs/btk/bin/blobtools", line 5, in <module>
    from blobtools import cli
ModuleNotFoundError: No module named 'blobtools'
```

**Comment by rjchallis** [comment]
I've just built a new release for blobtk that shouldn't need make or rust as the pip wheels for python3.9 built and made it to PyPI.

I'll be taking a look at improving blobtoolkit packaging, but meanwhile it's probably worth trying 
```
pip uninstall blobtk blobtoolkit
pip install --no-cache-dir blobtoolkit
```
in case a clean install helps

**Comment by Surbhigrewal** [comment]
This didn't work for the intel cpu mac.

I tried installing on a M1 Max cpu Mac and got errors for building the wheels for blobtk (because of cmake as above) but also for datrie (see below)

```
Building wheel for datrie (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for datrie (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_clib
      building 'datrie' library
      creating build
      creating build/temp.macosx-11.1-arm64-cpython-39
      creating build/temp.macosx-11.1-arm64-cpython-39/libdatrie
      creating build/temp.macosx-11.1-arm64-cpython-39/libdatrie/datrie
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/sbzsm11/mambaforge/envs/btk/include -arch arm64 -I/Users/sbzsm11/mambaforge/envs/btk/include -fPIC -O2 -isystem /Users/sbzsm11/mambaforge/envs/btk/include -arch arm64 -Ilibdatrie -c libdatrie/datrie/alpha-map.c -o build/temp.macosx-11.1-arm64-cpython-39/libdatrie/datrie/alpha-map.o
      xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))).
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for datrie
Failed to build blobtk datrie
```

so i created the env again with

`conda create -n btk python=3.9 cmake datrie -y`

and this seems to have worked!

**Comment by Surbhigrewal** [comment]
This didn't work for the intel cpu mac.

I tried installing on a M1 Max cpu Mac and got errors for building the wheels for blobtk (because of cmake as above) but also for datrie (see below)

Building wheel for datrie (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for datrie (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_clib
      building 'datrie' library
      creating build
      creating build/temp.macosx-11.1-arm64-cpython-39
      creating build/temp.macosx-11.1-arm64-cpython-39/libdatrie
      creating build/temp.macosx-11.1-arm64-cpython-39/libdatrie/datrie
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/sbzsm11/mambaforge/envs/btk/include -arch arm64 -I/Users/sbzsm11/mambaforge/envs/btk/include -fPIC -O2 -isystem /Users/sbzsm11/mambaforge/envs/btk/include -arch arm64 -Ilibdatrie -c libdatrie/datrie/alpha-map.c -o build/temp.macosx-11.1-arm64-cpython-39/libdatrie/datrie/alpha-map.o
      xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))).
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for datrie
Failed to build blobtk datrie
so i created the env again with

conda create -n btk python=3.9 cmake datrie -y

and this seems to have worked!
