### ISSUE TITLE
Bug in window_stats.py

### ISSUE THREAD

**Issue by muffato** [blobtoolkit/blobtoolkit#201]
Hi Rich.

I got an error in window_stats for two assemblies. See the info below.

Container: `docker.io/genomehubs/blobtoolkit-4.3.2`

Command:
```
btk pipeline window-stats \
        --in GCA_963281015.1.tsv \
        --window 0.1 --window 0.01 --window 1 --window 100000 --window 1000000 \
        --out GCA_963281015.1_window_stats.tsv
```

Error:
```
2024-01-18 03:23:21,066 [ERROR] could not convert string to float: ''
Traceback (most recent call last):
  File "/opt/conda/envs/btk_env/bin/btk", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/btk/btk.py", line 80, in cli
    sys.exit(subcommand())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/btk/lib/pipeline.py", line 11, in main
    cli("btk pipeline")
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtoolkit_pipeline.py", line 52, in cli
    sys.exit(subcommand(rename))
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/window_stats.py", line 217, in main
    raise err
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/window_stats.py", line 214, in main
    process_files(args)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/window_stats.py", line 168, in process_files
    lengths, chunks, interval = parse_chunked_values(args["--in"], args)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/window_stats.py", line 77, in parse_chunked_values
    values[seqid][header_keys[key]].append(float(row[idx]))
ValueError: could not convert string to float: ''
```

Input file: [GCA_963281015.1.tsv.zip](https://github.com/blobtoolkit/blobtoolkit/files/13977437/GCA_963281015.1.tsv.zip) or [GCA_963555575.1.tsv.zip](https://github.com/blobtoolkit/blobtoolkit/files/13977450/GCA_963555575.1.tsv.zip)

**Comment by rjchallis** [comment]
Hi Matthieu

Thanks for the bug report. This error is being thrown when trying to parse an empty value in the TSV as float. There is an empty value for GC_skew in each of these files when the window length at the end of a sequence is exactly 1, e.g. for `OY725470.1:5177000-5177001`:

```
OY725470.1	5176000	5177000	0.475	-0.015	-0.101	1.994	0.234	0.241	0.236	0.289	0.0	0.06	3.98	5.94	7.774	236	241	234	289	0	0	0	0	0	0	0	357.85
OY725470.1	5177000	5177001	0.0		1.0	0.0	0.0	0.0	1.0	0.0	0.0	0.0	0.0	0.0	0.0	1	0	0	0	0	0	0	0	0	0	0	255.0
OY725471.1	0	1000	0.468	-0.214	0.109	1.977	0.184	0.284	0.295	0.237	0.0	0.048	3.889	5.723	7.227	295	284	184	237	0	0	0	0	0	0	0	154.8

```

I've added a line to catch these errors so the new version 4.3.3 release should run fine on these files

**Comment by muffato** [comment]
I can confirm it works fine. Thank you !
