### ISSUE TITLE
Bug in `count_busco_genes.py`

### ISSUE THREAD

**Issue by muffato** [blobtoolkit/blobtoolkit#204]
Hi Rich,

We're testing the Nextflow pipeline on 120 species (the same batch Karen sent you in October) and found this error happening on 39 of them

```
Command executed:

  btk pipeline count-busco-genes \
      --in dir01 --in full_table.tsv \
      --mask GCA_963082955.1.bed \
      --out GCA_963082955.1_buscogenes.tsv
  
  cat <<-END_VERSIONS > versions.yml
  "SANGERTOL_BLOBTOOLKIT:BLOBTOOLKIT:COLLATE_STATS:BLOBTOOLKIT_COUNTBUSCOS":
      blobtoolkit: $(btk --version | cut -d' ' -f2 | sed 's/v//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/btk_env/bin/btk", line 8, in <module>
      sys.exit(cli())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/btk/btk.py", line 80, in cli
      sys.exit(subcommand())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/btk/lib/pipeline.py", line 11, in main
      cli("btk pipeline")
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtoolkit_pipeline.py", line 52, in cli
      sys.exit(subcommand(rename))
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/count_busco_genes.py", line 105, in main
      raise err
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/count_busco_genes.py", line 92, in main
      mask, header = parse_busco_summary(buscofile, mask, header)
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/count_busco_genes.py", line 48, in parse_busco_summary
      with tofile.open_file_handle(filename) as fh:
  AttributeError: __enter__
```
Example input files are here: [btk_count-busco-genes.zip](https://github.com/blobtoolkit/blobtoolkit/files/14051501/btk_count-busco-genes.zip)

This is using `docker.io/genomehubs/blobtoolkit:4.3.3`

**Comment by rjchallis** [comment]
Hi Matthieu
You have `--in dir01 --in full_table.tsv`, in your command, presumably instead of `--in dir01/full_table.tsv`. I just tried with the correct path and the command runs fine.

**Comment by muffato** [comment]
Ah right, thanks. That was the pointer I needed !

In summary, there is some Groovy code in the pipeline to turn the list of table paths into `--in path1 --in path2 ...`. That works fine when there are multiple tables because the Groovy object is a list.
When there is a single table, the Groovy object is a "path", whose enumeration method returns the components between `/`. So instead of spitting `--in dir01/full_table.tsv`, it does `--in dir01 --in full_table.tsv`. Will fix that now.
