### ISSUE TITLE
[generate-config] Error message when using an invalid accession number

### ISSUE THREAD

**Issue by muffato** [blobtoolkit/blobtoolkit#205]
Hi Rich,

When `generate-config` is called with an invalid accession number, it fails with a stack-trace:
```
$ btk pipeline generate-config xxx
2024-01-31 11:27:04.289 [INFO] Fetching assembly metadata
Traceback (most recent call last):
  File "/opt/conda/envs/btk_env/bin/btk", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/btk/btk.py", line 80, in cli
    sys.exit(subcommand())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/btk/lib/pipeline.py", line 11, in main
    cli("btk pipeline")
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtoolkit_pipeline.py", line 52, in cli
    sys.exit(subcommand(rename))
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/generate_config.py", line 736, in main
    meta = parse_assembly_meta(accession)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/lib/generate_config.py", line 399, in parse_assembly_meta
    root = ET.fromstring(xml)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/opt/conda/envs/btk_env/lib/python3.9/xml/etree/ElementTree.py", line 1717, in feed
    self.parser.Parse(data, False)
TypeError: a bytes-like object is required, not 'NoneType'
ERROR 1 Wed 31 Jan 11:27:04 GMT 2024
```

[The above is on the version 4.3.3 of the container]

Would it be possible to print a clearer error message ? That'll make it easier for users to spot what they did wrong.

Thank you,
Matthieu

**Comment by rjchallis** [comment]
Ah - I'd never run it with an invalid accession before. Building a 4.3.4 release with the fix now

**Comment by muffato** [comment]
Super, thank you !
