### ISSUE TITLE
BLAST output format columns order

### ISSUE THREAD

**Issue by gmartinezredondo** [blobtoolkit/blobtoolkit#29]
Hello!

I have used diamond to obtain hits with public databases and then filtered my data using Blobtools. I have used the commands specified on your webpage (https://blobtoolkit.genomehubs.org/blobtools2/blobtools2-tutorials/adding-data-to-a-dataset/adding-hits/), where it says that the order of columns in the diamond output file is: "qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore". In the following paragraph it says that: "The default value of 1=qseqid,2=staxids,3=bitscore,5=sseqid,10=sstart,11=send,14=evalue matches the output from the example commands above. Columns not listed in the default setting are not used."

However, according to this last paragraph, the 10th column corresponds to the subject alignment start position, while in the order specified on the diamond command, the 10th column is the query alignment start position. Am I right?
Is it a mistake in the tutorial? If it is, how does it affect the filtering?

Thank you in advance,

Gemma

**Comment by rjchallis** [comment]
Hi, thanks for reporting this

This looks like a bug in the code where the `sstart` and `send` labels are used, but the `qstart` and `qend` values are required, so it cancels itself out when using the standard column order. Fortunately, whichever values are used here won't affect the taxon assignment or the filtering as the actual positions are only used for presentation of the results in the viewer.

I'll get this fixed for the next release, but for now you'll need to keep using the wrong labels as `qstart` and `qend` would just be ignored by the `--hits-cols` param.

**Comment by gmartinezredondo** [comment]
Thank you very much for your reply!

**Comment by kmkocot** [comment]
Sorry, I am still confused. Is the mistake in the tutorial or the output of the blobtools help message? Will the fix you're going to make change the behavior of the software or just the help menu? Thanks!

**Comment by rjchallis** [comment]
This is a simple but confusing bug. The mistake is in the code, where the columns labeled `sstart` and `send` are treated as `qstart` and `qend`. The default columns in the help message works as it labels `qstart` `sstart`. 

The fix will change the code to use `qstart` as the label for `qstart`, and the help message (as shown in the tutorial) to use the correct labels. The list of diamond columns will stay unchanged. To keep things backward compatible for anyone who has hacked around this bug in the past, I'll also keep the mapping of the `sstart` label to the `qstart` column if `qstart` is not specified. 

I forgot to tag this issue when updating the code in the develop branch where the fix is available, but I'm getting a couple of other things in order ready for the next release so other code in that branch is changing a bit at the moment. I'll come back and close this issue once the release is ready and the code has made it to the main branch.

**Comment by mkyapchiongco** [comment]
Hi, sorry, I am trying to run this and I have the following order (following what is on the tutorial), is this correct? I was a bit confused on the wording above.
qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen sstart send qstart qend evalue bitscore

**Comment by kmkocot** [comment]
Sorry but I'm also confused about this still. Here's what I've been doing:
--outfmt 6 qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen sstart send qstart qend evalue bitscore

**Comment by rjchallis** [comment]
Sorry for all the confusion.  I've now updated the the text on that page and the associated code to fix the ordering. The default is:

```
--outfmt 6 qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore
```

if you have results run with a different order, this can be set during import, e.g.:

```
--outfmt 6 qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen sstart send qstart qend evalue bitscore
```

should be imported with:

```
--hits-cols 1=qseqid,2=staxids,3=bitscore,5=sseqid,12=qstart,13=qend,14=evalue
```

**Comment by kmkocot** [comment]
Thanks Richard. Sorry to keep bugging you, but I just downloaded and installed blobtools v2.6.1 and I just wanted to point out that when I run "blobtools add -h" it says:
```
--hits-cols LIST      Comma separated list of <column number>=<field name>.
[Default: 1=qseqid,2=staxids,3=bitscore,5=sseqid,10=qstart,11=qend,14=evalue]

```
I just wanted to make sure I have the correct version?

**Comment by rjchallis** [comment]
Hi Kevin. Yes that's the correct version with qstart and qend in cols 10 and 11 by default. 

(The import example in my last comment was in case you had results with these fields in cols 12 and 13 as you suggested in an earlier comment)

**Comment by pstrope** [comment]
I am also having trouble with adding the blast and diamond outputs. I want to first get the adding of the blast file working.
Could you please update the docs for what this link should be (in Adding Hits page)
`https://blobtoolkit.genomehubs.org/download/ALIAS/S_v/S_venezuelensis_HH1/S_venezuelensis_HH1.blastn.nt.root.1.minus.6247.out.gz`
Perhaps if there was a header in the blast output, we could be sure which column is what.
When adding, what should the `--hits_cols` argument be for the most recent blast output file? Thank you!

**Comment by kmkocot** [comment]
Sorry for all the posts here but I am still having issues and I think there may be an issue with version 2.6.1. Apologies in advance this is just operator error! Here's what I"m doing:

#Run this command just once to make the nr diamond database
diamond makedb --threads 1 --in /home/wirenia/databases/nr.gz --taxonmap /home/wirenia/databases/prot.accession2taxid.gz --taxonnodes /home/wirenia/databases/taxdump/nodes.dmp -d nr

#Search the genome assembly against the NCBI nr database with taxonomy information
#Note: there is disagreement about the order of columns in the blobtools create --help output and this site: https://blobtoolkit.genomehubs.org/blobtools2/blobtools2-tutorials/adding-data-to-a-dataset/adding-hits/
#See: https://github.com/blobtoolkit/blobtools2/issues/29
diamond blastx --threads 30 -c 1 --query final.purged.fa.PolcaCorrected.fa.masked --db /home/wirenia/databases/nr/nr.dmnd --outfmt 6 qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --sensitive --max-target-seqs 1 --evalue 1e-25 --out Hanleya.blast 

#Map trimmed PE reads to genome
minimap2 -ax sr -t 30 final.purged.fa.PolcaCorrected.fa.masked Hanleya_1P.fastq Hanleya_2P.fastq | samtools sort -@30 -O BAM -o Hanleya_trimmed_reads_to_genome.bam

#Create BlobDir
blobtools create --fasta final.purged.fa.PolcaCorrected.fa.masked --taxid 2732485 --taxdump /home/wirenia/databases/new_taxdump Hanleya_BlobDir

#Add data to BlobDir
#You may need to use the --hits-cols flag, making sure it matches what you did in your Diamond search above
blobtools add --threads 30 --taxdump /home/wirenia/databases/new_taxdump --busco full_table.tsv --cov Hanleya_trimmed_reads_to_genome.bam Hanleya_BlobDir

blobtools add --threads 30 --hits Hanleya.blast --taxdump /home/wirenia/databases/new_taxdump Hanleya_BlobDir


#View results
export BTK_FILE_PATH=/home/wirenia/Desktop/2021-06-09_Hanleya_blobtools/Hanleya_BlobDir
blobtools host --viewer /home/wirenia/bin/blobtools2/viewer `pwd`

The first blobtools add command works fine but the second one produces the following error:
`wirenia@wirenia:~/Desktop/2021-06-09_Hanleya_blobtools_checking_I_did_the_diamond_search_right$ blobtools add --threads 30 --hits Hanleya.blast Hanleya_BlobDir
Parsing taxdump
Traceback (most recent call last):
  File "/home/wirenia/bin/blobtools2/lib/add.py", line 194, in <module>
    main()
  File "/home/wirenia/bin/blobtools2/lib/add.py", line 141, in main
    taxdump = fetch_taxdump(args["--taxdump"])
  File "/home/wirenia/bin/blobtools2/lib/fetch.py", line 93, in fetch_taxdump
    taxdump = Taxdump(path_to_taxdump)
  File "/home/wirenia/bin/blobtools2/lib/taxdump.py", line 28, in __init__
    self.load_ranks()
  File "/home/wirenia/bin/blobtools2/lib/taxdump.py", line 39, in load_ranks
    filename = os.path.abspath(os.path.join(self.directory, 'nodes.dmp'))
  File "/home/wirenia/bin/anaconda3/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

Here's what the first line of Hanleya.blast looks like:
`scf7180000271244	588596	966	scf7180000271244	PKY53522.1	43.8	1162	482	16	8548	5570	267	1426	9.43e-302	966`

I did try using just one add command but that also did not work. Any ideas what the issue is? 

Thanks!
Kevin

**Comment by rjchallis** [comment]
Hi Kevin

This error is being thrown before it tries to parse Hanleya.blast, and suggests it can't find `/home/wirenia/databases/new_taxdump/nodes.dmp` - can you check that you have a node.dmp` file inside `/home/wirenia/databases/new_taxdump`?

**Comment by rjchallis** [comment]
@pstrope I've updated the link so it now points to the intended file at https://blobtoolkit.genomehubs.org/download/ALIAS/S_v/S_venezuelensis_HH1/S_venezuelensis_HH1.blastn.nt_v5.root.1.minus.6247.out.gz

The column order in this file is `qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue`, which should work with the default value for `--hits-cols`, as should any files generated with the example commands. 

I agree that a header row would make things easier but the code can't currently recognise header rows so I won't be able to add one to this file. There should generally be no need to use the `--hits-cols` option if importing files generated using the btk pipeline or using commands like the ones in the docs, but it is there in case you have a file with a different column order.

**Comment by kmkocot** [comment]
> Hi Kevin
> 
> This error is being thrown before it tries to parse Hanleya.blast, and suggests it can't find `/home/wirenia/databases/new_taxdump/nodes.dmp` - can you check that you have a node.dmp`file inside`/home/wirenia/databases/new_taxdump`?

Thank you Richard! I just checked and that file (/home/wirenia/databases/new_taxdump/nodes.dmp) does exist. I've tried re-downloading the new_taxdump from NCBI and I'm re-running the original script in case that .dmp file is somehow corrupted. I will let you know how it goes.

**Comment by tanpham15** [comment]
Hi, I solved the problem. When adding hits, not only `add --his-cols`, but also include parameters of `--taxrule`, `--taxdump`, `--evalue`, `--bitscore`, `--hit-count`.
