### ISSUE TITLE
interactive viewer mode not working in v. 3.0.0.0

### ISSUE THREAD

**Issue by capoony** [blobtoolkit/blobtoolkit#50]
Dear all, 

first of all, thanks for this wonderful tool. I newly installed via pip and everthing works like a charme. 

However, when I want to start Firefox via blobtools view, I get the following error message:

```bash
blobtools view \
>   --remote ${out}/results/AssemblyQC/blobtools \
>   --out ${out}/results/AssemblyQC/blobtools/out \
>   --interactive \
>   --view snail
Initializing viewer
Traceback (most recent call last):

  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/easyprocess/__init__.py", line 176, in start
    self.popen = subprocess.Popen(
  File "/opt/anaconda3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/blobtools-3.0.0/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/blobtools/blobtools.py", line 69, in cli
    sys.exit(subcommand())
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/blobtools/lib/view.py", line 442, in cli
    main(args)
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/blobtools/lib/view.py", line 418, in main
    interactive_view(args, loc, viewer, level)
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/blobtools/lib/view.py", line 340, in interactive_view
    driver, display = firefox_driver(args)
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/blobtools/lib/view.py", line 185, in firefox_driver
    display = Display(visible=0, size=(800, 600))
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/pyvirtualdisplay/display.py", line 54, in __init__
    self._obj = cls(
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/pyvirtualdisplay/xvfb.py", line 44, in __init__
    AbstractDisplay.__init__(
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/pyvirtualdisplay/abstractdisplay.py", line 88, in __init__
    helptext = get_helptext(program)
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/pyvirtualdisplay/util.py", line 10, in get_helptext
    p.call()
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/easyprocess/__init__.py", line 147, in call
    self.start().wait(timeout=timeout)
  File "/opt/venv/blobtools-3.0.0/lib/python3.8/site-packages/easyprocess/__init__.py", line 186, in start
    raise EasyProcessError(self, "start error")
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file
or directory: 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>
```

To work around the Xvfb error, I installed the Xvfb-server as follows:

```
yum install xorg-x11-server-Xvfb
```

But now, blobtools view gets stuck at

```
blobtools view \
>   --remote ${out}/results/AssemblyQC/blobtools \
>   --out ${out}/results/AssemblyQC/blobtools/out \
>   --interactive \
>   --view snail

Initializing viewer
Loading http://localhost:8001/view/blobtools/dataset/blobtools/snail
```
and does not proceed opening the Firefox browser

Thanks for your help, 

Martin

**Comment by rjchallis** [comment]
Thanks for letting me know about the xvfb error - I'll list the dependency in the README.

Your blobtools view command seems to be missing the directory so I'm not sure why it didn't throw an error parsing the command - `--remote` is a flag that doesn't take a value that doesn't make sense in combination with `--interactive`. so you command should probably look more like
```
blobtools view \
   --out ${out}/results/AssemblyQC/blobtools/out \
   --interactive \
   --view snail \
  /path/to/BlobDir
```

**Comment by capoony** [comment]
Thanks a lot for your swift response!!

I tried the command you suggested

```
blobtools view \
  --out ${out}/results/AssemblyQC/blobtools/out \
  --view snail \
  --interactive \
  ${out}/results/AssemblyQC/blobtools/datasets 
```

Unfortunately with the same result that Firefox does not open up. 

```
blobtools view \
>   --out ${out}/results/AssemblyQC/blobtools/out \
>   --view snail \
>   --interactive \
>   ${out}/results/AssemblyQC/blobtools/datasets
Initializing viewer
Loading http://localhost:8006/view/datasets/dataset/datasets/snail
```

Thanks a lot for your help!!
