### ISSUE TITLE
Issue in run_blobtools_create while running the BTK2 pipeline

### ISSUE THREAD

**Issue by aureliendejode** [blobtoolkit/blobtoolkit#54]
I got an error message for the run_blobtools_create rule of the pipeline while all the other steps went apparently well.
Do you know what is happening here ?
I tried to run the command interactively (I am working on a slurm cluster)
and here is what I get:

[aurli@r486 blobtools]$ blobtools replace             --bedtsvdir ../window_stats             --meta CADCXM01.meta.yaml             --taxdump /sw/data/ncbi_taxonomy/latest          --taxrule buscogenes  --busco ../busco/CADCXM01.busco.lepidoptera_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.endopterygota_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.insecta_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.arthropoda_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.metazoa_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.eukaryota_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.bacteria_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.archaea_odb10/full_table.tsv.gz            --hits ../diamond_blastp/CADCXM01.diamond.busco_genes.out             --evalue 1e-25             --hit-count 100000             --threads 4             CADCXM01.1

Reading all TSV files in ../window_stats
Parsing taxdump
Traceback (most recent call last):
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/add.py", line 194, in <module>
    main()
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/add.py", line 141, in main
    taxdump = fetch_taxdump(args["--taxdump"])
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/fetch.py", line 93, in fetch_taxdump
    taxdump = Taxdump(path_to_taxdump)
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/taxdump.py", line 30, in __init__
    self.load_ancestors()
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/taxdump.py", line 60, in load_ancestors
    for line in file_io.stream_file(filename):
TypeError: 'NoneType' object is not iterable

Do you have any idea what is happening ?
Thanks

**Comment by aureliendejode** [comment]
Hi,

So I have tried to run the pipeline in interactive mode and step by step.
All steps are going well, but when I arrive to the last one I get the following error message.

Command used:
snakemake -p           -j 4           --directory /proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/Blobtoolkit/Test_data2/blobtools           --configfile /proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/Blobtoolkit/Test_data2/config.yaml           --latency-wait 120           --stats /proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/Blobtoolkit/Test_data2/blobtools.stats           --restart-times 0           -s /proj/staff/niharika/blobtoolkit_test/pipeline/blobtools.smk

Error message:
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                     count    min threads    max threads
--------------------  -------  -------------  -------------
all                         1              1              1
run_blobtools_add           1              4              4
run_blobtools_create        1              4              4
total                       3              1              4

Select jobs to execute...

[Fri Mar  4 15:55:43 2022]
rule run_blobtools_create:
    input: ../window_stats/CADCXM01.window_stats.tsv, ../busco/CADCXM01.busco.lepidoptera_odb10/full_table.tsv.gz, ../diamond_blastp/CADCXM01.diamond.busco_genes.out, /sw/data/ncbi_taxonomy/latest, CADCXM01.meta.yaml
    output: CADCXM01.1/meta.json, CADCXM01.1/identifiers.json, CADCXM01.1/buscogenes_phylum.json, CADCXM01.1/ERR3313222_cov.json, CADCXM01.1/ERR3313317_cov.json, CADCXM01.1/ERR3313223_cov.json, CADCXM01.1/lepidoptera_odb10_busco.json
    log: logs/CADCXM01/run_blobtools_create.log
    jobid: 1
    benchmark: logs/CADCXM01/run_blobtools_create.benchmark.txt
    threads: 4
    resources: tmpdir=/scratch/25128178

blobtools replace             --bedtsvdir ../window_stats             --meta CADCXM01.meta.yaml             --taxdump /sw/data/ncbi_taxonomy/latest             --taxrule buscogenes             --busco ../busco/CADCXM01.busco.lepidoptera_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.endopterygota_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.insecta_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.arthropoda_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.metazoa_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.eukaryota_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.bacteria_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.archaea_odb10/full_table.tsv.gz             --hits ../diamond_blastp/CADCXM01.diamond.busco_genes.out             --evalue 1e-25             --hit-count 100000             --threads 4             CADCXM01.1 > logs/CADCXM01/run_blobtools_create.log 2>&1
Waiting at most 120 seconds for missing files.
MissingOutputException in line 1 of /proj/staff/niharika/blobtoolkit_test/pipeline/rules/run_blobtools_create.smk:
Job Missing files after 120 seconds:
CADCXM01.1/meta.json
CADCXM01.1/identifiers.json
CADCXM01.1/buscogenes_phylum.json
CADCXM01.1/ERR3313222_cov.json
CADCXM01.1/ERR3313317_cov.json
CADCXM01.1/ERR3313223_cov.json
CADCXM01.1/lepidoptera_odb10_busco.json
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 1 completed successfully, but some output files are missing. 1
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/Blobtoolkit/Test_data2/blobtools/.snakemake/log/2022-03-04T155542.741235.snakemake.log


Do you have an idea of what is going on ?

**Comment by aureliendejode** [comment]
Ok, after trying several times, changing the latency-wait to 800 and increasing the number of threads to 30.
I still get the following error:

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 30
Rules claiming more threads will be scaled down.
Job stats:
job                        count    min threads    max threads
-----------------------  -------  -------------  -------------
add_summary_to_metadata        1              1              1
all                            1              1              1
run_blobtools_add              1              4              4
run_blobtools_create           1              4              4
total                          4              1              4

Select jobs to execute...

[Fri Mar  4 17:05:03 2022]
rule add_summary_to_metadata:
    output: CADCXM01.meta.yaml
    log: logs/CADCXM01/add_summary_to_metadata.log
    jobid: 2
    benchmark: logs/CADCXM01/add_summary_to_metadata.benchmark.txt
    wildcards: assembly=CADCXM01
    resources: tmpdir=/scratch/25128178

/sw/bioinfo/BlobToolKit/2.6.4/rackham/btk_env/bin/python3.8 /crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/Blobtoolkit/Test_data2/blobtools/.snakemake/scripts/tmpzwkh
9icu.add_summary_to_metadata.py
[Fri Mar  4 17:05:07 2022]
Finished job 2.
1 of 4 steps (25%) done
Select jobs to execute...

[Fri Mar  4 17:05:07 2022]
rule run_blobtools_create:
    input: ../window_stats/CADCXM01.window_stats.tsv, ../busco/CADCXM01.busco.lepidoptera_odb10/full_table.tsv.gz, ../diamond_blastp/CADCXM01.diamond.busco_genes.out, /sw/data/ncbi_
taxonomy/latest, CADCXM01.meta.yaml
    output: CADCXM01.1/meta.json, CADCXM01.1/identifiers.json, CADCXM01.1/buscogenes_phylum.json, CADCXM01.1/ERR3313222_cov.json, CADCXM01.1/ERR3313317_cov.json, CADCXM01.1/ERR33132
23_cov.json, CADCXM01.1/lepidoptera_odb10_busco.json
    log: logs/CADCXM01/run_blobtools_create.log
    jobid: 1
    benchmark: logs/CADCXM01/run_blobtools_create.benchmark.txt
    threads: 4
    resources: tmpdir=/scratch/25128178

blobtools replace             --bedtsvdir ../window_stats             --meta CADCXM01.meta.yaml             --taxdump /sw/data/ncbi_taxonomy/latest             --taxrule buscogenes 
            --busco ../busco/CADCXM01.busco.lepidoptera_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.endopterygota_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco
.insecta_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.arthropoda_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.metazoa_odb10/full_table.tsv.gz --busco ../busco/
CADCXM01.busco.eukaryota_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.bacteria_odb10/full_table.tsv.gz --busco ../busco/CADCXM01.busco.archaea_odb10/full_table.tsv.gz    
         --hits ../diamond_blastp/CADCXM01.diamond.busco_genes.out             --evalue 1e-25             --hit-count 100000             --threads 4             CADCXM01.1 > logs/CA
DCXM01/run_blobtools_create.log 2>&1
Waiting at most 800 seconds for missing files.
MissingOutputException in line 1 of /proj/staff/niharika/blobtoolkit_test/pipeline/rules/run_blobtools_create.smk:
Job Missing files after 800 seconds:
CADCXM01.1/meta.json
CADCXM01.1/buscogenes_phylum.json
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 1 completed successfully, but some output files are missing. 1
Removing output files of failed job run_blobtools_create since they might be corrupted:
CADCXM01.1/identifiers.json, CADCXM01.1/ERR3313222_cov.json, CADCXM01.1/ERR3313317_cov.json, CADCXM01.1/ERR3313223_cov.json, CADCXM01.1/lepidoptera_odb10_busco.json
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/Blobtoolkit/Test_data2/blobtools/.snakemake/log/2022-03-04T170502.944499.snakemake.log

I checked and the following are files are indeed missing: CADCXM01.1/meta.json
CADCXM01.1/buscogenes_phylum.json.
So it looks like run_blobtools_create, manage to create the other files but not those 2 ones.

When I look at the logs I still get the same message:

more blobtools/logs/CADCXM01/run_blobtools_create.log
Reading all TSV files in ../window_stats
Parsing taxdump
Traceback (most recent call last):
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/add.py", line 194, in <module>
    main()
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/add.py", line 141, in main
    taxdump = fetch_taxdump(args["--taxdump"])
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/fetch.py", line 93, in fetch_taxdump
    taxdump = Taxdump(path_to_taxdump)
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/taxdump.py", line 30, in __init__
    self.load_ancestors()
  File "/sw/bioinfo/BlobToolKit/2.6.4/rackham/blobtools2/lib/taxdump.py", line 60, in load_ancestors
    for line in file_io.stream_file(filename):
TypeError: 'NoneType' object is not iterable


I am not sure why it managed to create some of the files and not the last 2 ?
Could it be a memory issue ?

**Comment by aureliendejode** [comment]
Hi,

I found the issue. Something was wrong with the taxdump on the cluster.
I downloaded a new own using the link in #32 and it solved the problem.
