### ISSUE TITLE
Filter to create summary table

### ISSUE THREAD

**Issue by o-william-white** [blobtoolkit/blobtoolkit#71]
Hello, 

I would like to use filter to create a summary table with the assembly information. I can create an blobtools object and add blast and mapping info no problem, but I hit an error that I cannot explain using filter. I am running the docker image of singularity via singularity. 

```
   singularity exec blobtoolkit_latest.sif blobtools create --fasta tmp_P25302_1097/ref_P25302_1097.fasta tmp_P25302_1097

   singularity exec blobtoolkit_latest.sif blobtools add \
      --hits tmp_P25302_1097/blastn_out_P25302_1097.txt \
      --taxrule bestsumorder \
      --taxdump /home/oliw/software/taxdump \
      tmp_P25302_1097

   singularity exec blobtoolkit_latest.sif blobtools add \
      --cov  tmp_P25302_1097/mapped_P25302_1097.bam\
      tmp_P25302_1097

   singularity exec blobtoolkit_latest.sif blobtools filter \
      --table tmp_P25302_1097/summary_table_P25302_1097.txt \
      --table-fields gc,length,bestsumorder_superkingdom,bestsumorder_phylum tmp_P25302_1097
```

When I run the filter command, I get the following error: 

```
Traceback (most recent call last):
  File "/home/blobtoolkit/miniconda3/envs/btk_env/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/home/blobtoolkit/miniconda3/envs/btk_env/lib/python3.8/site-packages/blobtools/blobtools.py", line 88, in cli
    sys.exit(subcommand())
  File "/home/blobtoolkit/miniconda3/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/filter.py", line 459, in cli
    main(args)
  File "/home/blobtoolkit/miniconda3/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/filter.py", line 355, in main
    file_io.write_file(args["--table"], table)
  File "/home/blobtoolkit/miniconda3/envs/btk_env/lib/python3.8/site-packages/blobtools/lib/file_io.py", line 143, in write_file
    fh.write(content)
TypeError: write() argument must be str, not list
```

Any suggestions would be much appreciated

Best wishes
Ollie

**Comment by edexter** [comment]
I am experiencing the same issue using blobtoolkit v4.3.11 on linux Ubuntu
