### ISSUE TITLE
Error message when using Filter

### ISSUE THREAD

**Issue by khoojj** [blobtoolkit/blobtoolkit#83]
Hi, I am trying to filter the fastq reads based on the phylum rank with the following:

```
blobtools filter \
     --query-string "http://localhost:8001/view/blobtools_out_megahit/dataset/blobtools_out_megahit/blob?bestsumorder_phylum--Keys=1%2C0&length--Min=500#Filters" \
     --fastq /pub59/jingk/04_chigger_mito01/reads/Sample_23832_1-CH13_1.fastq.gz \
     --fastq /pub59/jingk/04_chigger_mito01/reads/Sample_23832_1-CH13_2.fastq.gz \
     --cov ~/04_chigger_mito01/02_mitos+bowtie/220719_CH_test4/mt_assembly/megahit/megahit_out/final.contigs.sorted.bam \
     --summary filter_chordata \
     ~/04_chigger_mito01/04_blobtools/CH_megahit_220720/filter_chordata
```

And I keep getting the following error:

```
WARN: Skipping field 'bestsumorder_phylum', not present in dataset
WARN: Skipping field 'length', not present in dataset
Traceback (most recent call last):
  File "/pub59/jingk/miniconda3/envs/blobtools2/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/pub59/jingk/miniconda3/envs/blobtools2/lib/python3.8/site-packages/blobtools/blobtools.py", line 88, in cli
    sys.exit(subcommand())
  File "/pub59/jingk/miniconda3/envs/blobtools2/lib/python3.8/site-packages/blobtools/lib/filter.py", line 459, in cli
    main(args)
  File "/pub59/jingk/miniconda3/envs/blobtools2/lib/python3.8/site-packages/blobtools/lib/filter.py", line 293, in main
    indices = [index for index, value in enumerate(identifiers.values)]
AttributeError: 'bool' object has no attribute 'values'
```
Have I key in anything wrongly? 
Thanks!

**Comment by rjchallis** [comment]
Apologies that the error is not very informative - I've just made a change for the next release so in future the error should give a clearer idea of what is wrong. The warnings are related to being unable to read in the fields/identifiers for the BlobDir that you are filtering so I suspect `~/04_chigger_mito01/04_blobtools/CH_megahit_220720/filter_chordata` is an empty directory so if you change the last part of your command to use the correct path to the BlobDir the command should work.

**Comment by khoojj** [comment]
Noted! Yes, I changed it to the BlobDir and it worked. Thanks!
